FROM alpine:3.15
LABEL maintainer="Kien Nguyen-Tuan <kiennt2609@gmail.com>"
# environment variables
RUN apk update && \
    apk add --no-cache vim \
    git \
    fontconfig \
    powerline-extra-symbols \
    curl \
    ca-certificates
RUN adduser --disabled-password --gecos '' vimuser && \
    echo "ALL            ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers
WORKDIR /home/vimuser
ENV HOME /home/vimuser
COPY .vimrc $HOME/.vimrc
RUN chown vimuser:vimuser $HOME/.vimrc
USER vimuser
# setup vim-plug plugin manager
RUN curl -k -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
CMD vim
