name: Build and Push
on:
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * *

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Set safe directory # https://github.com/actions/checkout/issues/760
        run: |
          set -x
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory /github/workspace
    
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run buidl script
        run: |
          ls -la
          bash conductor/build-images.sh
        shell: bash
