name: Build and Push OpenSSl
on:
  push:
    branches:
      - master
    paths:
      - openssl/**
  pull_request:
    paths:
      - openssl/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:1.1.1'
          push: true
          tags: kiennt26/openssl:1.1.1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:1.1.0'
          push: true
          tags: kiennt26/openssl:1.1.0

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:3.0.8'
          push: true
          tags: kiennt26/openssl:3.0.8
